version: '3'
services:
  api-server:
    image: sethsamrat/server
    ports:
      - "8000:8000"
    networks:
      - mern-app
    container_name: server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
  react-app:
    image: sethsamrat/client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    command: npm start
networks:
  mern-app:
    driver: bridge